// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("21752480-73eb-4418-809c-d500d847427c"),
                            Address = "TW3 5RS",
                            DateOfBirth = new DateTime(2022, 8, 10, 10, 13, 5, 61, DateTimeKind.Local).AddTicks(8210),
                            FirstName = "John",
                            LastName = "Tim"
                        },
                        new
                        {
                            ClientId = new Guid("9f41ab02-6e52-4dda-8d44-738d70806114"),
                            Address = "SE2 2TR",
                            DateOfBirth = new DateTime(2022, 8, 10, 10, 13, 5, 61, DateTimeKind.Local).AddTicks(8280),
                            FirstName = "Sara",
                            LastName = "Sara"
                        },
                        new
                        {
                            ClientId = new Guid("694d7d35-7ddd-4eaf-930b-4db0e8191457"),
                            Address = "RE3 8UY",
                            DateOfBirth = new DateTime(2022, 8, 10, 10, 13, 5, 61, DateTimeKind.Local).AddTicks(8280),
                            FirstName = "Peter",
                            LastName = "Pin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
